sudo: false
language: java
jdk: openjdk11

install: mvn dependency:go-offline -B -V

script:
- mvn clean package

after_success:
- java -jar target/serialization-format-benchmarks.jar -c without -e roundTripAndCheckEquality

addons:
  apt:
    packages:
    - thrift-compiler

cache:
  directories:
  - $HOME/.m2
